### ISSUE TITLE
Adicionar una tarjeta que no tiene una url asociada

### ISSUE THREAD

**Issue by tegusg** [luisllamasbinaburo/Arduino-GestorURLsAdicionalesDeTarjetas#1]
Hola, muchas gracias por sus aportes, tenga un pequeño inconveniente no se si talvez pudiera orientarme, estoy usando un IDE llamado Energia IDE esta completamente basado en Arduino IDE y sirve para programar varias tarjetas de Texas Instrument, la cuestión es que en este link https://github.com/energia/c2000-core se encuestran las tarjetas que quiero adicionar con el gestor de tarjetas del IDE de esta manera https://energia.nu/guide/boards/ pero las tarjetas que necesito no están en el gestor (pero si en GitHub), hay alguna manera de instalarla directamente desde GitHub o como podria obtener la url para esta. 
Uso windows 10 y Energia 1.8.10E23
Muchas gracias

**Comment by luisllamasbinaburo** [comment]
No está relacionado con este repositorio. Tendrás que preguntar en el Github del IDE
